-- MySQL Script generated by MySQL Workbench
-- Thu Sep 22 16:32:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema thecnical_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `thecnical_test` ;

-- -----------------------------------------------------
-- Schema thecnical_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thecnical_test` DEFAULT CHARACTER SET utf8mb3 ;
USE `thecnical_test` ;

-- -----------------------------------------------------
-- Table `thecnical_test`.`pqr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thecnical_test`.`pqr` ;

CREATE TABLE IF NOT EXISTS `thecnical_test`.`pqr` (
  `id_pqr` INT NOT NULL AUTO_INCREMENT,
  `id_type_user` INT NOT NULL,
  `description` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `ticket_type` VARCHAR(255) NOT NULL,
  `ticket_status` VARCHAR(255) NOT NULL,
  `ticket_creation_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_pqr`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thecnical_test`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thecnical_test`.`users` ;

CREATE TABLE IF NOT EXISTS `thecnical_test`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(255) NOT NULL,
  `surnames` VARCHAR(255) NOT NULL,
  `mobile_phone` VARCHAR(255) NOT NULL,
  `landline` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `type_id` VARCHAR(255) NOT NULL,
  `number_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
